test

diff --git a/.github/workflows/Build DVLD_Project_App_Desktop.yml b/.github/workflows/Build DVLD_Project_App_Desktop.yml
--- a/.github/workflows/Build DVLD_Project_App_Desktop.yml
+++ b/.github/workflows/Build DVLD_Project_App_Desktop.yml
@@ -54,6 +54,22 @@ jobs:
           run: |
             echo "Windows Starting booting"
             docker compose up
+            echo "Starting Services in Background"
+            docker compose up -d
+
+            echo "Waiting 120 seconds for SQL Server to fully initialize..."
+            sleep 120 
+
+            echo "Attempting database RESTORE..."
             docker exec sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "$DB_PASSWORD" -Q "RESTORE DATABASE [DVLD] FROM DISK = '/backup_folder/DVLD_Backup.bak' WITH MOVE 'DVLD' TO '/var/opt/mssql/data/DVLD.mdf', MOVE 'DVLD_log' TO '/var/opt/mssql/data/DVLD_log.ldf', RECOVERY, REPLACE"
+            
+            if [ $? -ne 0 ]; then
+              echo "--- Database RESTORE Failed. Fetching SQL Server Logs for diagnosis ---"
+              docker logs sqlserver --tail 200
+              exit 1
+            fi
+            
+            echo "Database RESTORE completed successfully!"
+            
             echo "Remote web page:http://127.0.0.1:8006"
 
