test11

diff --git a/.github/workflows/Build DVLD_Project_App_Desktop.yml b/.github/workflows/Build DVLD_Project_App_Desktop.yml
--- a/.github/workflows/Build DVLD_Project_App_Desktop.yml
+++ b/.github/workflows/Build DVLD_Project_App_Desktop.yml
@@ -55,17 +55,17 @@ jobs:
             echo "Windows Starting booting"
             docker compose up -d
 
-             echo "Waiting 120 seconds for SQL Server to fully initialize..."
-             sleep 120 
-             echo "Attempting database RESTORE!"
-             docker exec sqlserver /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "$DB_PASSWORD" -C -Q "RESTORE DATABASE [DVLD] FROM DISK = '/backup_folder/DVLD_Backup.bak' WITH MOVE 'DVLD' TO '/var/opt/mssql/data/DVLD.mdf', MOVE 'DVLD_log' TO '/var/opt/mssql/data/DVLD_log.ldf', RECOVERY, REPLACE"
+            echo "Waiting 120 seconds for SQL Server to fully initialize..."
+            sleep 120 
+            echo "Attempting database RESTORE!"
+            docker exec sqlserver /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "$DB_PASSWORD" -C -Q "RESTORE DATABASE [DVLD] FROM DISK = '/backup_folder/DVLD_Backup.bak' WITH MOVE 'DVLD' TO '/var/opt/mssql/data/DVLD.mdf', MOVE 'DVLD_log' TO '/var/opt/mssql/data/DVLD_log.ldf', RECOVERY, REPLACE"
           
-             if [ $? -ne 0 ]; then
-               echo "--- Database RESTORE Failed. Fetching SQL Server Logs for diagnosis ---"
-               docker logs sqlserver --tail 200
-               exit 1
-             fi
+            if [ $? -ne 0 ]; then
+              echo "--- Database RESTORE Failed. Fetching SQL Server Logs for diagnosis ---"
+              docker logs sqlserver --tail 200
+              exit 1
+            fi
           
-             echo "Database RESTORE completed successfully!"
+            echo "Database RESTORE completed successfully!"
 
 
